from groq import Groq
from dotenv import load_dotenv
import os

# ---------------------------------------------------------
# 1. Load environment variables from .env
# ---------------------------------------------------------
# load_dotenv() loads variables from the .env file
# into the environment.
#
# Example .env:
# GROQ_API_KEY=your_api_key
# ---------------------------------------------------------
load_dotenv()


# ---------------------------------------------------------
# 2. Create Groq client
# ---------------------------------------------------------
# os.getenv("GROQ_API_KEY") retrieves the API key
# that we stored in the .env file.
#
# Groq() creates a client through which we can
# communicate with Groq's LLM models.
# ---------------------------------------------------------
client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)


# ---------------------------------------------------------
# 3. System Prompt
# ---------------------------------------------------------
# SYSTEM PROMPT:
# A system message defines the behavior, role, rules,
# and boundaries that we want the AI model to follow.
#
# It is different from a user prompt.
#
# System → HOW the model should behave
# User   → WHAT the user wants
# ---------------------------------------------------------

SYSTEM_PROMPT = """
You only answer coding-related questions.

If the user asks anything unrelated to coding,
respond with:
"No, I can't answer questions other than coding."
"""


# ---------------------------------------------------------
# 4. Send request to the LLM
# ---------------------------------------------------------
# client.chat.completions.create() sends our messages
# to the selected model.
#
# model:
# Specifies which LLM we want to use.
#
# messages:
# Contains the conversation between the system, user,
# and assistant.
# ---------------------------------------------------------

response = client.chat.completions.create(

    # The LLM model we are using
    model="openai/gpt-oss-120b",

    messages=[

        # -------------------------------------------------
        # SYSTEM MESSAGE
        # -------------------------------------------------
        # Gives instructions/rules to the model.
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        },

        # -------------------------------------------------
        # USER MESSAGE
        # -------------------------------------------------
        # This is the actual question asked by the user.
        {
            "role": "user",
            "content": "What is Generative AI? Explain in one sentence."
        }
    ]
)


# ---------------------------------------------------------
# 5. Extract and print the model's response
# ---------------------------------------------------------
# response contains the complete API response.
#
# response.choices[0]
#     → first generated response
#
# .message
#     → message object
#
# .content
#     → actual text generated by the model
# ---------------------------------------------------------

print(response.choices[0].message.content)